# This rule is not used by the project k8s-staticsite-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over web.mydomain.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-staticsite-operator
    app.kubernetes.io/managed-by: kustomize
  name: staticsite-admin-role
rules:
- apiGroups:
  - web.mydomain.com
  resources:
  - staticsites
  verbs:
  - '*'
- apiGroups:
  - web.mydomain.com
  resources:
  - staticsites/status
  verbs:
  - get
